#!/bin/sh

function clear_and_exit {
  if [ $? -eq 1 ]; then
      clear && exit
  fi
}

# Check if eth0 exists
if [ -z "$iface" ]; then
  if [ ! -e "/sys/class/net/eth0" ]; then
    # Prompt user for interface name
    iface=$(dialog --stdout --inputbox "Enter network interface name:" 0 0)
  else
    iface="eth0"
  fi
fi

clear_and_exit

# Prompt user for network configuration mode
if [ -z "$is_static" ]; then
  mode=$(dialog --stdout --inputbox "Do you want to use DHCP or set a static IP address? (dhcp/static):" 0 0)
  if [ "$mode" = "dhcp" ]; then
    is_static="false"
  else
    is_static="true"
  fi
fi

clear_and_exit

# Prompt for DNS Server
if [ -z "$dns_server" ]; then
  dns_server=$(dialog --stdout --inputbox "Enter DNS server address (Enter 1.1.1.1 if unsure):" 0 0)
fi

clear_and_exit

# Changes files
if [ "$is_static" = "false" ]; then
  # Write DHCP configuration to /etc/network/interfaces
  cat << EOF > /etc/network/interfaces
  auto $iface
  iface $iface inet dhcp
  dns-nameservers $dns_server
EOF
else
  # Prompt user for network configuration values
  if [ -z "$ip_addr" ]; then
    ip_addr=$(dialog --stdout --inputbox "Enter IP address:" 0 0)
  fi 
  clear_and_exit
  if [ -z "$subnet_mask" ]; then
    subnet_mask=$(dialog --stdout --inputbox "Enter subnet mask:" 0 0)
  fi
  clear_and_exit
  if [ -z "$gateway_addr" ]; then
    gateway_addr=$(dialog --stdout --inputbox "Enter gateway address:" 0 0)
  fi
  clear_and_exit
  # Write static IP configuration to /etc/network/interfaces
  cat << EOF > /etc/network/interfaces
  auto $iface
  iface $iface inet static
    address $ip_addr
    netmask $subnet_mask
    gateway $gateway_addr
    dns-nameservers $dns_server
EOF
fi

# Restart networking service
service networking restart

