#!/bin/bash

#if [[ $(cat ../version == "") ]]
#  /usr/share/achilles/common
#else
#  ~/Projects/iOS/Achilles/configs/usr/share/achilles/common
#fi

dialog=dialog

if [ "$EUID" -ne 0 ]
  then
  $dialog --clear --title "Warning!" \
        --msgbox "Please run as root!" 0 0
  clear
  exit
fi

# Define the arrays
iface=$(ls /sys/class/net | grep -v -e 'eth' -e 'lo' | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g')
ip link set $iface up
array2=()
while IFS= read -r line; do
    array2+=("$line")
done < <(iwctl station $iface get-networks | sed -e '1,4d' -e 's/\(open\|psk\|8021x\).*//' -e 's/\x1B\[.\{1,3\}//g' -e 's/^[[:space:]]*//' -e 's/^0m>//g' -e 's/^[[:space:]]*//' | sed '/^$/d')
array2+=("")
array2+=("Hidden Network")
number=0
array1=()
stopcode=false
for i in ${!array2[@]}; do
  if [ $stopcode = true ]; then
    number=$((${#array2[@]} -1))
  else
    number=$((number + 1))
  fi
  if [ $number = $((${#array2[@]} - 1)) ]; then
    array1+=("")
    stopcode=true
  else
    array1+=($number)
  fi
done
if [ "$iface" = "" ]
  then
  msg="Enter network interface name out of this list (likley wlan[number] or wlp*): \n \n"
  msg+=$(ls /sys/class/net/ | sed 's/\x1B\[[0-9;]*[mK]//g')
  # Prompt user for interface name
  iface=$($dialog --stdout --inputbox "$msg" 0 0)
fi

if [ $? -eq 1 ]; then
    clear
    exit
fi

# Define the option list for --menu dynamically based on the arrays
option_list=()
for i in ${!array1[@]}; do
  option_list+=("${array2[$i]}" "${array1[$i]}")
done

# Define the selected option
while true; do

selected_option=$($dialog --clear --title "$currentnetwork" \
    --menu "Choose one of the following options:" 0 0 0 \
    "${option_list[@]}" 3>&1 1>&2 2>&3)

if [ $? -eq 1 ]; then
    clear 
    exit
fi

if [ "$selected_option" = "" ]; then
  continue
else
  break
fi

done

if [ "$selected_option" = "Hidden Network" ]; then
  msg="Enter network name:"
  selected_option=$($dialog --stdout --title "Enter Network Name" --inputbox "$msg" 0 0)
  echo "$selected_option"
fi

if [ $? -eq 1 ]; then
    clear
    exit
fi

# Display the password prompt
password=$($dialog --clear --title "Enter Password" \
    --insecure --passwordbox "Enter the password for $selected_option (if open leave empty):" 0 0 3>&1 1>&2 2>&3)

if [ $? -eq 1 ]; then
    clear
    exit
fi


echo $iface > /tmp/logiwd
echo $selected_option >> /tmp/logiwd
echo $password >> /tmp/logiwd
iwctl station $iface disconnect
if [ "$password" = "" ]; then
  echo "open" >> /tmp/logiwd
  iwctl station $iface connect $selected_option
else
  echo "psk" >> /tmp/logiwd
  iwctl station $iface connect $selected_option -P $password
fi

if [ $? -eq 1 ]; then
  $dialog --clear --title "Connection Failed!" \
    --msgbox "You probably entered the password wrong, or tried to connect to 8021x." 0 0
else
  $dialog --clear --title "Connected" \
    --msgbox "You have connect to $selected_option" 0 0
fi

if [ $? -eq 1 ]; then
   clear
   exit
fi

clear
exit
